"""create table costs

Revision ID: 7a6c7e07d589
Revises: 0f5db295f507
Create Date: 2024-10-07 22:17:11.643422

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a6c7e07d589'
down_revision: Union[str, None] = '0f5db295f507'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('costs',
    sa.Column('cost_per_hour', sa.Integer(), nullable=False),
    sa.Column('cost_of_selected_position', sa.Integer(), nullable=False),
    sa.Column('cost_of_accepted_position', sa.Integer(), nullable=False),
    sa.Column('cost_of_packaged_position', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('costs')
    # ### end Alembic commands ###
