"""create tables costs

Revision ID: 757773c664f7
Revises: b37e4801f854
Create Date: 2024-10-10 17:14:48.957904

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '757773c664f7'
down_revision: Union[str, None] = 'b37e4801f854'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('costs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cost_per_hour', sa.Integer(), nullable=False),
    sa.Column('cost_of_selected_position', sa.Integer(), nullable=False),
    sa.Column('cost_of_accepted_position', sa.Integer(), nullable=False),
    sa.Column('cost_of_packaged_position', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),

    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], name=op.f('fk_costs_employee_id_employees')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_costs'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('costs')
    # ### end Alembic commands ###
