"""create tables salaries

Revision ID: 781ec703d237
Revises: 4e4b75271756
Create Date: 2024-10-10 17:12:39.535861

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '781ec703d237'
down_revision: Union[str, None] = '4e4b75271756'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('salaries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.BIGINT(), nullable=False),
    sa.Column('add_date', sa.DATETIME(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], name=op.f('fk_salaries_employee_id_employees')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_salaries'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('salaries')
    # ### end Alembic commands ###
